#!/bin/sh

#
# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (c) 2025 sark02
#

set -e

in=$1
out=$2
if [ "X-$1" = "X-" -o "X-$2" = "X-" ]; then
    echo "usage: $0 infile outfile" >&2
    exit 1
fi
if [ ! -f $in ]; then
    echo "$in: not found" >&2
    exit 1
fi

$(dirname $0)/mklzgmini.pl < $in > $out
patch -d $(dirname $out) < $(dirname $0)/mklzgmini.patch
