#!/bin/bash

#
# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (c) 2025 sark02
#

set -e

if [ $# -ne 9 ]; then
    echo "usage: $0 boot main dmasfx psgsfx readme license howto outstfile outzipfile" >&2
    exit 1
fi

if [ -e DEFENDER ]; then
    echo "DEFENDER: exists - will not overwrite" >&2
    exit 1
fi

boot=$1
main=$2
dma=$3
psg=$4
readme=$5
license=$6
howto=$7
outstfile=$8
outzipfile=$9

# Create .st disk file
image_opt="-i $outstfile"
dd if=/dev/zero of=$outstfile bs=1k count=720 status=none
mformat -f 720 -a $image_opt ::
./tools/mkdisk.py $boot $outstfile
mcopy $image_opt $main ::DEFENDER.TOS
mcopy $image_opt $dma ::DMASFX.BIN
mcopy $image_opt $psg ::PSGSFX.BIN
mcopy $image_opt -t $readme ::README.TXT
mcopy $image_opt -t $howto ::HOWTO.TXT
mcopy $image_opt -t $license ::LICENSE.TXT

# Create .zip file
mkdir DEFENDER
mcopy $image_opt ::DEFENDER.TOS ::DMASFX.BIN ::PSGSFX.BIN ::README.TXT ::HOWTO.TXT ::LICENSE.TXT DEFENDER/
rm -f $outzipfile
zip -q $outzipfile DEFENDER/*
rm -rf DEFENDER

