#!/bin/bash

#
# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (c) 2025 sark02
#

TAG=$(git describe --tags --abbrev=0 2>/dev/null)
VERSION=$(echo "$TAG" | sed 's/^v//')
if git describe --tags --exact-match >/dev/null 2>&1; then
    echo "$VERSION RELEASE"
else
    echo "$VERSION+ DEVEL"
fi
