#!/bin/bash

#
# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (c) 2025 sark02
#

set -e

if [ $# -ne 9 ]; then
    echo "usage: $0 boot main dmasfx psgsfx readme license howto outstfile outzipfile" >&2
    exit 1
fi

if [ -e DEFENDER ]; then
    echo "DEFENDER: exists - will not overwrite" >&2
    exit 1
fi

boot=$1
main=$2
dma=$3
psg=$4
readme=$5
license=$6
howto=$7
outstfile=$8
outzipfile=$9

# Create .st disk file
cat << EOF > $HOME/.mtoolsrc
drive a:
  file="$(pwd)/$outstfile"
EOF
dd if=/dev/zero of=$outstfile bs=1k count=720 status=none
mformat -f 720 -a a:
./tools/mkdisk.py $boot $outstfile
mcopy $main a:DEFENDER.TOS
mcopy $dma a:DMASFX.BIN
mcopy $psg a:PSGSFX.BIN
mcopy -t $readme a:README.TXT
mcopy -t $howto a:HOWTO.TXT
mcopy -t $license a:LICENSE.TXT

# Create .zip file
mkdir DEFENDER
mcopy a:DEFENDER.TOS a:DMASFX.BIN a:PSGSFX.BIN a:README.TXT a:HOWTO.TXT a:LICENSE.TXT DEFENDER/
rm -f $outzipfile
zip -q $outzipfile DEFENDER/*
rm -rf DEFENDER

